// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqwpEmny6U_SS9insh5r4Rnn_5c2bqwLc',
    appId: '1:473589416044:web:873c6c03c05daf7534d849',
    messagingSenderId: '473589416044',
    projectId: 'projhup-e1544',
    authDomain: 'projhup-e1544.firebaseapp.com',
    storageBucket: 'projhup-e1544.firebasestorage.app',
    measurementId: 'G-WDJ8C6Y2MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5O1_I-q2TrHc3Gj9WmFXi2nKonLbCfic',
    appId: '1:473589416044:android:3f04481e19118a0634d849',
    messagingSenderId: '473589416044',
    projectId: 'projhup-e1544',
    storageBucket: 'projhup-e1544.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiuKSNH_GGpmhjG_A_1puna-wmNFW29qM',
    appId: '1:473589416044:ios:074ff8bf5001011134d849',
    messagingSenderId: '473589416044',
    projectId: 'projhup-e1544',
    storageBucket: 'projhup-e1544.firebasestorage.app',
    iosBundleId: 'com.example.onboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiuKSNH_GGpmhjG_A_1puna-wmNFW29qM',
    appId: '1:473589416044:ios:074ff8bf5001011134d849',
    messagingSenderId: '473589416044',
    projectId: 'projhup-e1544',
    storageBucket: 'projhup-e1544.firebasestorage.app',
    iosBundleId: 'com.example.onboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqwpEmny6U_SS9insh5r4Rnn_5c2bqwLc',
    appId: '1:473589416044:web:7e4e37e2023f11de34d849',
    messagingSenderId: '473589416044',
    projectId: 'projhup-e1544',
    authDomain: 'projhup-e1544.firebaseapp.com',
    storageBucket: 'projhup-e1544.firebasestorage.app',
    measurementId: 'G-J9W19SJ26K',
  );
}
